108 contact examples and fixes
GazzolaLab/PyElastica pull request #109
Opened 2022-06-11 19:05 UTC by armantekinalp

Fixes #108 and also we added example cases for rod-cylinder contact.

2022-06-11 19:09 UTC, skim0119 requested changes

2022-06-11 19:09 UTC, skim0119 commented on examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
> +tip_collision = True
Capitalize flag?

2022-06-11 19:09 UTC, skim0119 commented on examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
> +if True:
Flag name?

2022-06-11 19:09 UTC, skim0119 commented on examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
> +    def plot_video(
These should be in `post_processing.py`, right?

2022-06-11 19:09 UTC, skim0119 commented on examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
> +        if True:
Flag name

2022-06-11 19:09 UTC, skim0119 commented on examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_with_y_normal.py
> +if True:
Flag name

2022-06-11 20:14 UTC, armantekinalp commented
Flags capitalized and post-processing scripts are moved to `post_processing.py` file.

2022-06-12 00:35 UTC, skim0119 approved these changes
LGTM

2022-06-12 01:39 UTC, merged