refactor EndPointForcesSinusoidal example and test cases
GazzolaLab/PyElastica pull request #110
Opened 2022-06-11 20:37 UTC by armantekinalp

Fixes #103 . This fix is required for implementing pyproject for PyElastica.

2022-06-12 20:33 UTC, bhosale2 requested changes
LGTM mostly, 2 minor requests.

2022-06-12 20:33 UTC, bhosale2 commented on elastica/external_forces.py
> +        # self.roll_direction = np.cross(tangent_direction, normal_direction)
remove?

2022-06-12 20:33 UTC, bhosale2 commented on elastica/external_forces.py
> +    """Applies sinusoidal forces on endpoints"""
maybe docstring here better reflects the comments you have below?

2022-06-13 00:11 UTC, skim0119 requested changes
Can you add the `EndpointForcesSinusoidal` on documentation?

2022-06-13 00:49 UTC, armantekinalp commented on elastica/external_forces.py
> +        # self.roll_direction = np.cross(tangent_direction, normal_direction)
Done.

2022-06-13 00:50 UTC, armantekinalp commented
I added documentation. Could you check again and then we can merge.

2022-06-13 18:53 UTC, skim0119 commented
here: https://github.com/armantekinalp/PyElastica/blob/103_refactor_EndpointForcesSinusoidal/docs/api/external_forces.rst

2022-06-16 15:49 UTC, bhosale2 approved these changes
LGTM.

2022-06-17 14:19 UTC, skim0119 approved these changes
LGTM

2022-06-17 14:19 UTC, merged