Refactor: changed Union[] typings to SystemType or RodType
GazzolaLab/PyElastica pull request #191
Opened 2022-08-19 18:41 UTC by sy-cui

1. Removed all Union[Type[RodBase], Type[RigidBodyBase]] to typing.SystemType in boundary_condition.py and dissipation.py.
2. Changed 'rod' passed to arguments to 'system' where typing is 'SystemType'
3. Changed 'SystemType' in HelicalBucklingBC to RodType
4. AnalyticalLinearDamper class in dissipation.py remains applicable to SystemType, but RigidBodyBase doesn't have system.dilatation so it may raise an error

2022-08-20 19:03 UTC, bhosale2 requested changes

2022-08-20 19:03 UTC, bhosale2 commented on elastica/dissipation.py
> +            self.rotational_damping_coefficient, system.dilatation
maybe we should revert this back? since currently `dilatation` is not defined for rigid bodies

2022-08-21 06:27 UTC, bhosale2 commented on elastica/dissipation.py
> +            self.rotational_damping_coefficient, system.dilatation
f079abb

2022-08-21 06:33 UTC, bhosale2 approved these changes
LGTM. @skim0119 please take over.

2022-08-21 18:17 UTC, skim0119 approved these changes

2022-08-21 18:18 UTC, merged