WIP: Task 3: Pytest for wrapper classes part 1
GazzolaLab/PyElastica pull request #262
Opened 2023-06-06 21:18 UTC by Rahul-JOON

This PR contains the test case for the wrapper class - ExternalContact as mentioned in #99 

Because the codebase is not broken, all of the test cases are currently passing.

2023-06-06 22:25 UTC, armantekinalp requested changes
Can we add one more test for two rods without collision

2023-06-06 22:25 UTC, armantekinalp commented on tests/test_contact_wrapper_classes.py
> +def test_external_contact_with_collision():
```suggestion
def test_external_contact_rod_rigid_body_with_collision():
```

2023-06-06 22:25 UTC, armantekinalp commented on tests/test_contact_wrapper_classes.py
> +def test_external_contact_without_collision():
```suggestion
def test_external_contact_rod_rigid_body_without_collision():
```

2023-06-06 22:25 UTC, armantekinalp commented on tests/test_contact_wrapper_classes.py
> +def test_external_contact_with_two_rods():
```suggestion
def test_external_contact_two_rods_with_collision():
```

2023-06-06 22:41 UTC, Rahul-JOON commented
Sure thing! I will add that test.

2023-06-07 13:39 UTC, armantekinalp approved these changes
LGTM thanks

2023-06-08 06:56 UTC, bhosale2 approved these changes
LGTM

2023-06-08 06:56 UTC, merged